<<<<<<< HEAD
import requests 
import pandas

hospitalization=requests.get('https://jhucoronavirus.azureedge.net/jhucoronavirus/hospitalization_by_state.json')
hospitalization=hospitalization.json()
# change the .json into a list

for i in range (0,len(hospitalization)):
    each=hospitalization[i]
# every element, in form of a dict, in the list is the data for a single state

    state=each['state']
    data=each['data']
    inpatient=data['inpatient']
    icu=data['icu']
# the data is separated into two dicts

    inpatient=pandas.DataFrame.from_dict(inpatient,orient='index')
    icu=pandas.DataFrame.from_dict(icu,orient='index')
# dataframe the dict

    inpatient.columns=['percentage']
    icu.columns=['percentage']
# fill the name of the column

    inpatient.to_csv('C:/Git/Power-Pill/Main/output/{}_inpatient.csv'.format(state))
    icu.to_csv('C:/Git/Power-Pill/Main/output/{}_icu.csv'.format(state))
# generate a .csv whose name can be filled with the state name automatically
=======
#hospitalization for all states in last two weeks
import requests
import pandas

hospitalization = requests.get(
    'https://jhucoronavirus.azureedge.net/jhucoronavirus/hospitalization_by_state.json'
) #get a .json from the website
hospitalization = hospitalization.json() #change the .json into a list
for i in range(
        0, len(hospitalization)
): #the list contains data for all states, files will be generated by state one by one
    each = hospitalization[
        i] #every element, in form of a dict, in the list is the data for a single state
    state = each[
        'state'] #the dict contains two elements while one is the abbreviaton for the name of the state
    data = each['data'] #the other is the exact data in form of another dict
    inpatient = data[
        'inpatient'] #the data is separated into a 'inpatient' part and
    icu = data['icu'] #a 'icu' part in form a dict
    inpatient = pandas.DataFrame.from_dict(
        inpatient, orient='index') #change the dict into .csv
    inpatient.columns = ['percentage'] #make the .csv more clear
    icu = pandas.DataFrame.from_dict(icu,
                                     orient='index') #change the dict into .csv
    icu.columns = ['percentage'] #make the .csv more clear
    inpatient.to_csv(
        'C:/Git/Power-Pill/Main/output/{}_inpatient.csv'.format(state)
    ) #generate a .csv whose name can be filled with the state name automatically
    icu.to_csv(
        'C:/Git/Power-Pill/Main/output/{}_icu.csv'.format(state)
    ) #generate a .csv whose name can be filled with the state name automatically

>>>>>>> 92ec19a89621524288f5de777d303045fd7877c5
